server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location /pdfjs/ {
        try_files $uri =404;
    }

    location /pdfjs/docs/ {
        alias /srv/sw25/pdf/;
        add_header Accept-Ranges bytes;
    }

    location /image/ {
        alias /srv/sw25/image/;
        try_files $uri =404;
    }
}
